### ISSUE TITLE
GPL Licensing?

### ISSUE THREAD

**Issue by darkdreamingdan** [ltworf/typedload#90]
Hello

I'm a big fan of this library and have used it in personal projects, but can't use it at work.

I'd love to use at my company and contribute to this library, but we can't due to the copyleft.  Is there a specific reason for GPL 3.0? Any chance a more permissive license could be used? MIT/BSD or LGPL?

**Comment by ltworf** [comment]
Hello,

I'm very very against permissive licenses such as MIT, especially because they allow corporations to take without giving anything back, and I don't see why would I ever work for free for some entity.

You might have noticed that there is an LGPL exception for the company where I work, where we also use this library, and which resulted in many contributions to this project done during working hours. So in the end it was a good move for me to put that exception.

So I've been thinking that for a one off money contribution I might add another LGPL exception.

Best.

**Comment by ltworf** [comment]
No response, closing.
